from proto_utils.generated.parsers import dtypes_pb2 as dtypes_pb2
from proto_utils.parsers import dtypes as dtypes

class DTypesSerde:
    @staticmethod
    def serialize_ast_type(ast_type: dtypes.AstType) -> dtypes_pb2.AstType: ...
    @staticmethod
    def deserialize_ast_type(proto: dtypes_pb2.AstType) -> dtypes.AstType: ...
    @staticmethod
    def serialize_ref_type(ref_type: dtypes.RefType) -> dtypes_pb2.RefType: ...
    @staticmethod
    def deserialize_ref_type(proto: dtypes_pb2.RefType) -> dtypes.RefType: ...
    @staticmethod
    def serialize_ast(ast: dtypes.AST) -> dtypes_pb2.AST: ...
    @staticmethod
    def deserialize_ast(proto: dtypes_pb2.AST) -> dtypes.AST: ...
    @staticmethod
    def serialize_token(token: dtypes.Token) -> dtypes_pb2.Tokens.Token: ...
    @staticmethod
    def deserialize_token(proto: dtypes_pb2.Tokens.Token) -> dtypes.Token: ...
    @staticmethod
    def serialize_tokens(tokens: dtypes.Tokens) -> dtypes_pb2.Tokens: ...
    @staticmethod
    def deserialize_tokens(proto: dtypes_pb2.Tokens) -> dtypes.Tokens: ...
