from proto_utils.generated.parsers import sql_builder_pb2 as sql_builder_pb2
from proto_utils.parsers import dtypes as dtypes
from proto_utils.parsers.ddl_generator_serde import DDLGeneratorSerde as DDLGeneratorSerde

class SQLBuilderSerde:
    @staticmethod
    def serialize_request_column_info(info: dtypes.SQLRequestColumnInfo) -> sql_builder_pb2.BuildSQLRequest.ColumnInfo: ...
    @staticmethod
    def deserialize_request_column_info(proto: sql_builder_pb2.BuildSQLRequest.ColumnInfo) -> dtypes.SQLRequestColumnInfo: ...
    @staticmethod
    def serialize_build_sql_request(request: dtypes.BuildSQLRequest) -> sql_builder_pb2.BuildSQLRequest: ...
    @staticmethod
    def deserialize_build_sql_request(proto: sql_builder_pb2.BuildSQLRequest) -> dtypes.BuildSQLRequest: ...
    @staticmethod
    def serialize_sql_response_sql_content(content: dtypes.SQLResponseSQLContent) -> sql_builder_pb2.BuildSQLResponse.SQLContent: ...
    @staticmethod
    def deserialize_sql_response_sql_content(proto: sql_builder_pb2.BuildSQLResponse.SQLContent) -> dtypes.SQLResponseSQLContent: ...
    @staticmethod
    def serialize_build_sql_response_content(content: dtypes.BuildSQLResponseContent) -> sql_builder_pb2.BuildSQLResponse.Content: ...
    @staticmethod
    def deserialize_build_sql_response_content(proto: sql_builder_pb2.BuildSQLResponse.Content) -> dtypes.BuildSQLResponseContent: ...
    @staticmethod
    def serialize_build_sql_response(response: dtypes.BuildSQLResponse) -> sql_builder_pb2.BuildSQLResponse: ...
    @staticmethod
    def deserialize_build_sql_response(proto: sql_builder_pb2.BuildSQLResponse) -> dtypes.BuildSQLResponse: ...
