# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
    prometheus:
        image: prom/prometheus:latest
        user: root
        volumes:
            - prometheus-data:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time=3d"
        networks:
            - monitoring
        ports:
            - published: 9090
              target: 9090
              protocol: tcp
              mode: host
        deploy:
            placement:
                constraints:
                    - node.role == manager
            resources:
                limits:
                    memory: 512M

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /:/rootfs:ro
            - /var/run:/var/run
            - /sys:/sys:ro
            - /var/lib/docker:/var/lib/docker:ro
        command:
            - "--docker_only=true"
        networks:
            - monitoring
        ports:
            - 8080:8080
        deploy:
            mode: global
            labels:
                - prometheus-job=cadvisor
            resources:
                limits:
                    memory: 256M

    node-exporter:
        image: prom/node-exporter:latest
        volumes:
            - /:/rootfs:ro
            - /sys:/host/sys:ro
            - /proc:/host/proc:ro
        command:
            - "--path.procfs=/host/proc"
            - "--path.sysfs=/host/sys"
            - "--path.rootfs=/rootfs"
        networks:
            - monitoring
        ports:
            - 9100:9100
        deploy:
            mode: global
            labels:
                - prometheus-job=node-exporter

    scaler:
        image: vulcan99/autoscaler:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            PROMETHEUS_URL: http://prometheus:9090
            STACK_NAME: dev
            CHECK_INTERVAL: 30
            COOLDOWN_PERIOD: 180
            METRIC_WINDOW_MULTIPLIER: 4
        networks:
            - monitoring
        deploy:
            placement:
                constraints:
                    - node.role == manager

    test-app:
        image: nginx:latest
        networks:
            - monitoring
        ports:
            - published: 8081
              target: 80
              protocol: tcp
              mode: host
        deploy:
            replicas: 1
            labels:
                - scaler.enabled=true
                - scaler.min=1
                - scaler.max=5
                - scaler.metric=cpu
                - scaler.up=10
                - scaler.down=2

networks:
    monitoring:

volumes:
    prometheus-data:
