# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
    prometheus:
        image: prom/prometheus:latest
        user: root
        volumes:
            - prometheus-data:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time=3d"
        networks:
            - monitoring
        ports:
            - published: 9090
              target: 9090
              protocol: tcp
              mode: ingress
        deploy:
            placement:
                constraints:
                    - node.role == manager
            resources:
                limits:
                    memory: 512M

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /:/rootfs:ro
            - /var/run:/var/run
            - /sys:/sys:ro
            - /var/lib/docker:/var/lib/docker:ro
        command:
            - "--docker_only=true"
        networks:
            - monitoring
        deploy:
            mode: global
            labels:
                - prometheus-job=cadvisor
            resources:
                limits:
                    memory: 256M

    node-exporter:
        image: prom/node-exporter:latest
        volumes:
            - /:/rootfs:ro
            - /sys:/host/sys:ro
            - /proc:/host/proc:ro
        command:
            - "--path.procfs=/host/proc"
            - "--path.sysfs=/host/sys"
            - "--path.rootfs=/rootfs"
        networks:
            - monitoring
        deploy:
            mode: global
            labels:
                - prometheus-job=node-exporter

    scaler:
        image: vulcan99/autoscaler:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            NODE_ENV: development
            PROMETHEUS_URL: ${SCALER_PROMETHEUS_URL}
            STACK_NAME: ${GLOBAL_STACK_NAME}
            CHECK_INTERVAL: ${SCALER_CHECK_INTERVAL}
            COOLDOWN_PERIOD: ${SCALER_COOLDOWN_PERIOD}
            METRIC_WINDOW_MULTIPLIER: ${SCALER_METRIC_WINDOW_MULTIPLIER}
        networks:
            - monitoring
        deploy:
            placement:
                constraints:
                    - node.role == manager

    formula-parser:
        image: vulcan99/formula-parser:latest
        environment:
            FORMULA_PARSER_HOST: ${PARSERS_FORMULA_PARSER_HOST}
            FORMULA_PARSER_PORT: ${PARSERS_FORMULA_PARSER_PORT}
            DEBUG_FORMULA_PARSER: ${PARSERS_DEBUG_FORMULA_PARSER}
        networks:
            - monitoring
            - parsers
        deploy:
            replicas: 1
            resources:
                reservations:
                    memory: "128m"
                limits:
                    memory: "256m"
            labels:
                - scaler.enabled=true

    ddl-generator:
        image: vulcan99/ddl-generator:latest
        environment:
            DDL_GENERATOR_HOST: ${PARSERS_DDL_GENERATOR_HOST}
            DDL_GENERATOR_PORT: ${PARSERS_DDL_GENERATOR_PORT}
            DDL_GENERATOR_DEBUG: ${PARSERS_DDL_GENERATOR_DEBUG}
        networks:
            - monitoring
            - parsers
        deploy:
            replicas: 1
            resources:
                reservations:
                    memory: "256m"
                limits:
                    memory: "512m"
            labels:
                - scaler.enabled=true

    sql-builder:
        image: vulcan99/sql-builder:latest
        environment:
            SQL_BUILDER_HOST: ${PARSERS_SQL_BUILDER_HOST}
            SQL_BUILDER_PORT: ${PARSERS_SQL_BUILDER_PORT}
            SQL_BUILDER_DEBUG: ${PARSERS_SQL_BUILDER_DEBUG}
        networks:
            - monitoring
            - parsers
        deploy:
            replicas: 1
            resources:
                reservations:
                    memory: "256m"
                limits:
                    memory: "512m"
            labels:
                - scaler.enabled=true

    excel-reader:
        image: vulcan99/excel-reader:latest
        environment:
            FORMULA_PARSER_HOST: "formula-parser"
            FORMULA_PARSER_PORT: ${PARSERS_FORMULA_PARSER_PORT}
            DDL_GENERATOR_HOST: "ddl-generator"
            DDL_GENERATOR_PORT: ${PARSERS_DDL_GENERATOR_PORT}
            SQL_BUILDER_HOST: "sql-builder"
            SQL_BUILDER_PORT: ${PARSERS_SQL_BUILDER_PORT}
            EXCEL_READER_HOST: ${PARSERS_EXCEL_READER_HOST}
            EXCEL_READER_PORT: ${PARSERS_EXCEL_READER_PORT}
            EXCEL_READER_DEBUG: ${PARSERS_EXCEL_READER_DEBUG}
        networks:
            - monitoring
            - parsers
        deploy:
            replicas: 1
            resources:
                reservations:
                    memory: "512m"
                limits:
                    memory: "1024m"
            labels:
                - scaler.enabled=true

    rabbitmq:
        image: rabbitmq:4-management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
        networks:
            - monitoring
            - rabbit
        ports:
            - published: 5672
              target: 5672
              protocol: tcp
              mode: ingress

            - published: 15672
              target: 15672
              protocol: tcp
              mode: ingress
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        deploy:
            replicas: 1
            resources:
                reservations:
                    memory: "512m"
                limits:
                    memory: "1024m"

    mongo:
        image: mongo:7.0
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        networks:
            - monitoring
            - mongo
        ports:
            - published: 27017
              target: 27017
              protocol: tcp
              mode: ingress
        volumes:
            - mongo-data:/data/db
        deploy:
            replicas: 1
            resources:
                reservations:
                    memory: "512m"
                limits:
                    memory: "1024m"

    redis:
        image: redis:7-alpine
        command:
            - "redis-server"
            - "--requirepass"
            - "${REDIS_PASSWORD}"
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        networks:
            - monitoring
            - redis
        ports:
            - published: 6379
              target: 6379
              protocol: tcp
              mode: ingress
        volumes:
            - redis-data:/data
        deploy:
            replicas: 1
            resources:
                reservations:
                    memory: "256m"
                limits:
                    memory: "512m"

    postgres:
        image: postgres:17
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /var/lib/postgresql/data/pgdata
        networks:
            - monitoring
            - postgres
        ports:
            - published: 5431
              target: 5432
              protocol: tcp
              mode: ingress
        volumes:
            - postgres-data:/var/lib/postgresql/data
        deploy:
            replicas: 1
            resources:
                reservations:
                    memory: "256m"
                limits:
                    memory: "512m"

    database:
        image: vulcan99/database:latest
        environment:
            MONGO_HOST: mongo
            MONGO_PORT: 27017
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_DB: ${MONGO_DB}
            MONGO_SCHEMAS_COLLECTION: ${MONGO_SCHEMAS_COLLECTION}
            MONGO_TASKS_COLLECTION: ${MONGO_TASKS_COLLECTION}
            MONGO_MAX_RETRIES: ${MONGO_MAX_RETRIES}
            MONGO_RETRY_DELAY_SECONDS: ${MONGO_RETRY_DELAY_SECONDS}
            MONGO_RETRY_BACKOFF_FACTOR: ${MONGO_RETRY_BACKOFF_FACTOR}

            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_DB: ${REDIS_DB}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            REDIS_EXPIRE_SECONDS: ${REDIS_EXPIRE_SECONDS}
            REDIS_MAX_RETRIES: ${REDIS_MAX_RETRIES}
            REDIS_RETRY_DELAY_SECONDS: ${REDIS_RETRY_DELAY_SECONDS}
            REDIS_RETRY_BACKOFF_FACTOR: ${REDIS_RETRY_BACKOFF_FACTOR}

            DATABASE_CONNECTION_HOST: ${DATABASE_CONNECTION_HOST}
            DATABASE_CONNECTION_PORT: ${DATABASE_CONNECTION_PORT}
            DATABASE_CONNECTION_DEBUG: ${DATABASE_CONNECTION_DEBUG}

            TASK_TTL_PENDING_SECONDS: ${TASK_TTL_PENDING_SECONDS}
            TASK_TTL_PROCESSING_SECONDS: ${TASK_TTL_PROCESSING_SECONDS}
            TASK_TTL_COMPLETED_SECONDS: ${TASK_TTL_COMPLETED_SECONDS}
            TASK_TTL_PUBLISHED_SECONDS: ${TASK_TTL_PUBLISHED_SECONDS}
            TASK_TTL_FAILED_SECONDS: ${TASK_TTL_FAILED_SECONDS}

            USER_CACHE_TTL_SECONDS: ${USER_CACHE_TTL_SECONDS}
            USER_LIST_CACHE_TTL_SECONDS: ${USER_LIST_CACHE_TTL_SECONDS}
            SCHEMA_CACHE_TTL_SECONDS: ${SCHEMA_CACHE_TTL_SECONDS}

            DEFAULT_TTL_SECONDS: ${DEFAULT_TTL_SECONDS}
        networks:
            - monitoring
            - mongo
            - redis
            - grpc
        deploy:
            replicas: 1
            resources:
                reservations:
                    memory: "512m"
                limits:
                    memory: "1024m"
            labels:
                - scaler.enabled=true

    typechecking:
        image: vulcan99/typechecking
        environment:
            MINIMAL_SERVER_HOST: ${DATABASE_CONNECTION_HOST}
            MINIMAL_SERVER_PORT: ${DATABASE_CONNECTION_PORT}
            MINIMAL_SERVER_DEBUG: ${DATABASE_CONNECTION_DEBUG}

            RABBITMQ_HOST: rabbitmq
            RABBITMQ_PORT: 5672
            RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_VHOST: ${RABBITMQ_DEFAULT_VHOST}
            RABBITMQ_MAX_RETRIES: ${RABBITMQ_MAX_RETRIES}
            RABBITMQ_RETRY_DELAY_SECONDS: ${RABBITMQ_RETRY_DELAY_SECONDS}
            RABBITMQ_BACKOFF_MULTIPLIER: ${RABBITMQ_BACKOFF_MULTIPLIER}
            RABBITMQ_THRESHOLD_SECONDS: ${RABBITMQ_THRESHOLD_SECONDS}

            MAX_WORKERS: ${MAX_WORKERS}
            WORKER_PREFETCH_COUNT: ${WORKER_PREFETCH_COUNT}

            DATABASE_CONNECTION_HOST: database
            DATABASE_CONNECTION_PORT: ${DATABASE_CONNECTION_PORT}
            DATABASE_MAX_RETRIES: ${DATABASE_MAX_RETRIES}
            DATABASE_RETRY_DELAY_SECONDS: ${DATABASE_RETRY_DELAY_SECONDS}
            DATABASE_BACKOFF_MULTIPLIER: ${DATABASE_BACKOFF_MULTIPLIER}
        networks:
            - monitoring
            - rabbit
            - grpc
        deploy:
            replicas: 1
            resources:
                reservations:
                    memory: "768m"
                limits:
                    memory: "1536m"
            labels:
                - scaler.enabled=true

networks:
    monitoring:
    parsers:
    redis:
    postgres:
    mongo:
    rabbit:
    grpc:

volumes:
    prometheus-data:
    rabbitmq-data:
    mongo-data:
    redis-data:
    postgres-data:
