name: "Build Docker Image"
description: "Build and verify Docker image for a service"

inputs:
  service_name:
    description: "Name of the service to build"
    required: true
  verify_image:
    description: "Verify the image was built successfully"
    required: false
    default: "true"
  registry_username:
    description: "Docker registry username (e.g., DockerHub username)"
    required: false
    default: ""
  registry_password:
    description: "Docker registry password (e.g., DockerHub password or token)"
    required: false
    default: ""
  image_name:
    description: "Name of the Docker image to build"
    required: false
    default: ""
  image_tag:
    description: "Tag for the Docker image"
    required: false
    default: "latest"
  push_image:
    description: "Push the Docker image to a registry after building"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: moonrepo/setup-toolchain@v0
      with:
        auto-install: true

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .moon/cache
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}

    - name: Build Docker image
      shell: bash
      run: |
        IMAGE_BASE="${{ inputs.image_name || inputs.service_name }}"

        if [ -n "${{ inputs.registry_username }}" ]; then
          IMAGE_FULL="${{ inputs.registry_username }}/${IMAGE_BASE}:${{ inputs.image_tag }}"
        else
          IMAGE_FULL="${IMAGE_BASE}:${{ inputs.image_tag }}"
        fi

        echo "Building image: $IMAGE_FULL"
        moon run ${{ inputs.service_name }}:docker-build -- -t "$IMAGE_FULL"

    - name: Verify Docker image
      if: inputs.verify_image == 'true'
      shell: bash
      run: |
        IMAGE_NAME="${{ inputs.image_name || inputs.service_name }}"
        if docker images | grep -q "$IMAGE_NAME"; then
          echo "Docker image '$IMAGE_NAME' built successfully"
          docker images | grep "$IMAGE_NAME"
        else
          echo "Docker image '$IMAGE_NAME' not found"
          exit 1
        fi

    - name: Show all Docker images
      if: always()
      shell: bash
      run: docker images

    - name: Log in to Docker Hub
      if: inputs.push_image == 'true' && inputs.registry_username != '' && inputs.registry_password != ''
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Push Docker image
      if: inputs.push_image == 'true'
      shell: bash
      run: |
        IMAGE_BASE="${{ inputs.image_name || inputs.service_name }}"
        if [ -n "${{ inputs.registry_username }}" ]; then
          IMAGE_FULL="${{ inputs.registry_username }}/${IMAGE_BASE}:${{ inputs.image_tag }}"
        else
          IMAGE_FULL="${IMAGE_BASE}:${{ inputs.image_tag }}"
        fi

        echo "Pushing image: $IMAGE_FULL"
        docker push "$IMAGE_FULL"
