# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sql_builder.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'sql_builder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import clients.ddl_generator_pb2 as ddl__generator__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sql_builder.proto\x12\x0bsql_builder\x1a\x13\x64\x64l_generator.proto\"\x8d\x02\n\x0f\x42uildSQLRequest\x12\x34\n\x04\x63ols\x18\x01 \x03(\x0b\x32&.sql_builder.BuildSQLRequest.ColsEntry\x12\x38\n\x06\x64types\x18\x02 \x03(\x0b\x32(.sql_builder.BuildSQLRequest.DtypesEntry\x12\x12\n\ntable_name\x18\x03 \x01(\t\x1aG\n\tColsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.ddl_generator.DDLResponse:\x02\x38\x01\x1a-\n\x0b\x44typesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xde\x01\n\x10\x42uildSQLResponse\x12;\n\x07\x63ontent\x18\x01 \x03(\x0b\x32*.sql_builder.BuildSQLResponse.ContentEntry\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x1a\x17\n\x08Sentence\x12\x0b\n\x03sql\x18\x01 \x03(\t\x1aV\n\x0c\x43ontentEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x35\n\x05value\x18\x02 \x01(\x0b\x32&.sql_builder.BuildSQLResponse.Sentence:\x02\x38\x01\x42\x08\n\x06_error2U\n\nSQLBuilder\x12G\n\x08\x42uildSQL\x12\x1c.sql_builder.BuildSQLRequest\x1a\x1d.sql_builder.BuildSQLResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sql_builder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUILDSQLREQUEST_COLSENTRY']._loaded_options = None
  _globals['_BUILDSQLREQUEST_COLSENTRY']._serialized_options = b'8\001'
  _globals['_BUILDSQLREQUEST_DTYPESENTRY']._loaded_options = None
  _globals['_BUILDSQLREQUEST_DTYPESENTRY']._serialized_options = b'8\001'
  _globals['_BUILDSQLRESPONSE_CONTENTENTRY']._loaded_options = None
  _globals['_BUILDSQLRESPONSE_CONTENTENTRY']._serialized_options = b'8\001'
  _globals['_BUILDSQLREQUEST']._serialized_start=56
  _globals['_BUILDSQLREQUEST']._serialized_end=325
  _globals['_BUILDSQLREQUEST_COLSENTRY']._serialized_start=207
  _globals['_BUILDSQLREQUEST_COLSENTRY']._serialized_end=278
  _globals['_BUILDSQLREQUEST_DTYPESENTRY']._serialized_start=280
  _globals['_BUILDSQLREQUEST_DTYPESENTRY']._serialized_end=325
  _globals['_BUILDSQLRESPONSE']._serialized_start=328
  _globals['_BUILDSQLRESPONSE']._serialized_end=550
  _globals['_BUILDSQLRESPONSE_SENTENCE']._serialized_start=429
  _globals['_BUILDSQLRESPONSE_SENTENCE']._serialized_end=452
  _globals['_BUILDSQLRESPONSE_CONTENTENTRY']._serialized_start=454
  _globals['_BUILDSQLRESPONSE_CONTENTENTRY']._serialized_end=540
  _globals['_SQLBUILDER']._serialized_start=552
  _globals['_SQLBUILDER']._serialized_end=637
# @@protoc_insertion_point(module_scope)
