from _typeshed import Incomplete
from proto_utils.database import dtypes as dtypes
from proto_utils.database.database_serde import DatabaseSerde as DatabaseSerde
from proto_utils.database.mongo_serde import MongoSerde as MongoSerde
from proto_utils.database.redis_serde import RedisSerde as RedisSerde
from proto_utils.generated.database.database_pb2_grpc import DatabaseServiceStub as DatabaseServiceStub

class DatabaseClient:
    channel: Incomplete
    stub: Incomplete
    def __init__(self, channel: str) -> None: ...
    def close(self) -> None: ...
    def redis_get_keys(self, request: dtypes.RedisGetKeysRequest) -> dtypes.RedisGetKeysResponse: ...
    def redis_set(self, request: dtypes.RedisSetRequest) -> dtypes.RedisSetResponse: ...
    def redis_get(self, request: dtypes.RedisGetRequest) -> dtypes.RedisGetResponse: ...
    def redis_delete(self, request: dtypes.RedisDeleteRequest) -> dtypes.RedisDeleteResponse: ...
    def redis_ping(self, request: dtypes.RedisPingRequest = None) -> dtypes.RedisPingResponse: ...
    def redis_get_cache(self, request: dtypes.RedisGetCacheRequest = None) -> dtypes.RedisGetCacheResponse: ...
    def clear_cache(self, request: dtypes.RedisClearCacheRequest = None) -> dtypes.RedisClearCacheResponse: ...
    def mongo_insert_one_schema(self, request: dtypes.MongoInsertOneSchemaRequest) -> dtypes.MongoInsertOneSchemaResponse: ...
    def mongo_count_all_documents(self, request: dtypes.MongoCountAllDocumentsRequest = None) -> dtypes.MongoCountAllDocumentsResponse: ...
    def mongo_find_jsonschema(self, request: dtypes.MongoFindJsonSchemaRequest) -> dtypes.MongoFindJsonSchemaResponse: ...
    def mongo_update_one_jsonschema(self, request: dtypes.MongoUpdateOneJsonSchemaRequest) -> dtypes.MongoUpdateOneJsonSchemaResponse: ...
    def mongo_delete_one_jsonschema(self, request: dtypes.MongoDeleteOneJsonSchemaRequest) -> dtypes.MongoDeleteOneJsonSchemaResponse: ...
    def mongo_delete_import_name(self, request: dtypes.MongoDeleteImportNameRequest) -> dtypes.MongoDeleteImportNameResponse: ...
    def update_task_id(self, request: dtypes.UpdateTaskIdRequest) -> dtypes.UpdateTaskIdResponse: ...
    def get_task_id(self, request: dtypes.GetTaskIdRequest) -> dtypes.GetTaskIdResponse: ...
    def get_tasks_by_import_name(self, request: dtypes.GetTasksByImportNameRequest) -> dtypes.GetTasksByImportNameResponse: ...
    def set_task_id(self, request: dtypes.SetTaskIdRequest) -> dtypes.SetTaskIdResponse: ...
