from proto_utils.database import dtypes as dtypes
from proto_utils.database.utils_serde import DatabaseUtilsSerde as DatabaseUtilsSerde
from proto_utils.generated.database import database_pb2 as database_pb2

class DatabaseSerde:
    @staticmethod
    def serialize_update_task_id_request(request: dtypes.UpdateTaskIdRequest) -> database_pb2.UpdateTaskIdRequest: ...
    @staticmethod
    def deserialize_update_task_id_request(proto: database_pb2.UpdateTaskIdRequest) -> dtypes.UpdateTaskIdRequest: ...
    @staticmethod
    def serialize_update_task_id_response(response: dtypes.UpdateTaskIdResponse) -> database_pb2.UpdateTaskIdResponse: ...
    @staticmethod
    def deserialize_update_task_id_response(proto: database_pb2.UpdateTaskIdResponse) -> dtypes.UpdateTaskIdResponse: ...
    @staticmethod
    def serialize_set_task_id_request(request: dtypes.SetTaskIdRequest) -> database_pb2.SetTaskIdRequest: ...
    @staticmethod
    def deserialize_set_task_id_request(proto: database_pb2.SetTaskIdRequest) -> dtypes.SetTaskIdRequest: ...
    @staticmethod
    def serialize_set_task_id_response(response: dtypes.SetTaskIdResponse) -> database_pb2.SetTaskIdResponse: ...
    @staticmethod
    def deserialize_set_task_id_response(proto: database_pb2.SetTaskIdResponse) -> dtypes.SetTaskIdResponse: ...
    @staticmethod
    def serialize_get_task_id_request(request: dtypes.GetTaskIdRequest) -> database_pb2.GetTaskIdRequest: ...
    @staticmethod
    def deserialize_get_task_id_request(proto: database_pb2.GetTaskIdRequest) -> dtypes.GetTaskIdRequest: ...
    @staticmethod
    def serialize_get_task_id_response(response: dtypes.GetTaskIdResponse) -> database_pb2.GetTaskIdResponse: ...
    @staticmethod
    def deserialize_get_task_id_response(proto: database_pb2.GetTaskIdResponse) -> dtypes.GetTaskIdResponse: ...
    @staticmethod
    def serialize_get_tasks_by_import_name_request(request: dtypes.GetTasksByImportNameRequest) -> database_pb2.GetTasksByImportNameRequest: ...
    @staticmethod
    def deserialize_get_tasks_by_import_name_request(proto: database_pb2.GetTasksByImportNameRequest) -> dtypes.GetTasksByImportNameRequest: ...
    @staticmethod
    def serialize_get_tasks_by_import_name_response(response: dtypes.GetTasksByImportNameResponse) -> database_pb2.GetTasksByImportNameResponse: ...
    @staticmethod
    def deserialize_get_tasks_by_import_name_response(proto: database_pb2.GetTasksByImportNameResponse) -> dtypes.GetTasksByImportNameResponse: ...
