from proto_utils.database import dtypes as dtypes
from proto_utils.database.utils_serde import DatabaseUtilsSerde as DatabaseUtilsSerde
from proto_utils.generated.database import mongo_pb2 as mongo_pb2

class MongoSerde:
    @staticmethod
    def serialize_insert_one_schema_request(request: dtypes.MongoInsertOneSchemaRequest) -> mongo_pb2.MongoInsertOneSchemaRequest: ...
    @staticmethod
    def deserialize_insert_one_schema_request(proto: mongo_pb2.MongoInsertOneSchemaRequest) -> dtypes.MongoInsertOneSchemaRequest: ...
    @staticmethod
    def serialize_insert_one_schema_response(response: dtypes.MongoInsertOneSchemaResponse) -> mongo_pb2.MongoInsertOneSchemaResponse: ...
    @staticmethod
    def deserialize_insert_one_schema_response(proto: mongo_pb2.MongoInsertOneSchemaResponse) -> dtypes.MongoInsertOneSchemaResponse: ...
    @staticmethod
    def serialize_count_all_documents_request(request: dtypes.MongoCountAllDocumentsRequest = None) -> mongo_pb2.MongoCountAllDocumentsRequest: ...
    @staticmethod
    def deserialize_count_all_documents_request(proto: mongo_pb2.MongoCountAllDocumentsRequest) -> dtypes.MongoCountAllDocumentsRequest: ...
    @staticmethod
    def serialize_count_all_documents_response(response: dtypes.MongoCountAllDocumentsResponse) -> mongo_pb2.MongoCountAllDocumentsResponse: ...
    @staticmethod
    def deserialize_count_all_documents_response(proto: mongo_pb2.MongoCountAllDocumentsResponse) -> dtypes.MongoCountAllDocumentsResponse: ...
    @staticmethod
    def serialize_find_jsonschema_request(request: dtypes.MongoFindJsonSchemaRequest) -> mongo_pb2.MongoFindJsonSchemaRequest: ...
    @staticmethod
    def deserialize_find_jsonschema_request(proto: mongo_pb2.MongoFindJsonSchemaRequest) -> dtypes.MongoFindJsonSchemaRequest: ...
    @staticmethod
    def serialize_find_jsonschema_response(response: dtypes.MongoFindJsonSchemaResponse) -> mongo_pb2.MongoFindJsonSchemaResponse: ...
    @staticmethod
    def deserialize_find_jsonschema_response(proto: mongo_pb2.MongoFindJsonSchemaResponse) -> dtypes.MongoFindJsonSchemaResponse: ...
    @staticmethod
    def serialize_update_one_jsonschema_request(request: dtypes.MongoUpdateOneJsonSchemaRequest) -> mongo_pb2.MongoUpdateOneJsonSchemaRequest: ...
    @staticmethod
    def deserialize_update_one_jsonschema_request(proto: mongo_pb2.MongoUpdateOneJsonSchemaRequest) -> dtypes.MongoUpdateOneJsonSchemaRequest: ...
    @staticmethod
    def serialize_update_one_jsonschema_response(response: dtypes.MongoUpdateOneJsonSchemaResponse) -> mongo_pb2.MongoUpdateOneJsonSchemaResponse: ...
    @staticmethod
    def deserialize_update_one_jsonschema_response(proto: mongo_pb2.MongoUpdateOneJsonSchemaResponse) -> dtypes.MongoUpdateOneJsonSchemaResponse: ...
    @staticmethod
    def serialize_delete_one_jsonschema_request(request: dtypes.MongoDeleteOneJsonSchemaRequest) -> mongo_pb2.MongoDeleteOneJsonSchemaRequest: ...
    @staticmethod
    def deserialize_delete_one_jsonschema_request(proto: mongo_pb2.MongoDeleteOneJsonSchemaRequest) -> dtypes.MongoDeleteOneJsonSchemaRequest: ...
    @staticmethod
    def serialize_delete_one_jsonschema_response(response: dtypes.MongoDeleteOneJsonSchemaResponse) -> mongo_pb2.MongoDeleteOneJsonSchemaResponse: ...
    @staticmethod
    def deserialize_delete_one_jsonschema_response(proto: mongo_pb2.MongoDeleteOneJsonSchemaResponse) -> dtypes.MongoDeleteOneJsonSchemaResponse: ...
    @staticmethod
    def serialize_delete_import_name_request(request: dtypes.MongoDeleteImportNameRequest) -> mongo_pb2.MongoDeleteImportNameRequest: ...
    @staticmethod
    def deserialize_delete_import_name_request(proto: mongo_pb2.MongoDeleteImportNameRequest) -> dtypes.MongoDeleteImportNameRequest: ...
    @staticmethod
    def serialize_delete_import_name_response(response: dtypes.MongoDeleteImportNameResponse) -> mongo_pb2.MongoDeleteImportNameResponse: ...
    @staticmethod
    def deserialize_delete_import_name_response(proto: mongo_pb2.MongoDeleteImportNameResponse) -> dtypes.MongoDeleteImportNameResponse: ...
