from proto_utils.database import dtypes as dtypes
from proto_utils.generated.database import redis_pb2 as redis_pb2

class RedisSerde:
    @staticmethod
    def serialize_get_keys_request(request: dtypes.RedisGetKeysRequest) -> redis_pb2.RedisGetKeysRequest: ...
    @staticmethod
    def deserialize_get_keys_request(proto: redis_pb2.RedisGetKeysRequest) -> dtypes.RedisGetKeysRequest: ...
    @staticmethod
    def serialize_get_keys_response(response: dtypes.RedisGetKeysResponse) -> redis_pb2.RedisGetKeysResponse: ...
    @staticmethod
    def deserialize_get_keys_response(proto: redis_pb2.RedisGetKeysResponse) -> dtypes.RedisGetKeysResponse: ...
    @staticmethod
    def serialize_set_request(request: dtypes.RedisSetRequest) -> redis_pb2.RedisSetRequest: ...
    @staticmethod
    def deserialize_set_request(proto: redis_pb2.RedisSetRequest) -> dtypes.RedisSetRequest: ...
    @staticmethod
    def serialize_set_response(response: dtypes.RedisSetResponse) -> redis_pb2.RedisSetResponse: ...
    @staticmethod
    def deserialize_set_response(proto: redis_pb2.RedisSetResponse) -> dtypes.RedisSetResponse: ...
    @staticmethod
    def serialize_get_request(request: dtypes.RedisGetRequest) -> redis_pb2.RedisGetRequest: ...
    @staticmethod
    def deserialize_get_request(proto: redis_pb2.RedisGetRequest) -> dtypes.RedisGetRequest: ...
    @staticmethod
    def serialize_get_response(response: dtypes.RedisGetResponse) -> redis_pb2.RedisGetResponse: ...
    @staticmethod
    def deserialize_get_response(proto: redis_pb2.RedisGetResponse) -> dtypes.RedisGetResponse: ...
    @staticmethod
    def serialize_delete_request(request: dtypes.RedisDeleteRequest) -> redis_pb2.RedisDeleteRequest: ...
    @staticmethod
    def deserialize_delete_request(proto: redis_pb2.RedisDeleteRequest) -> dtypes.RedisDeleteRequest: ...
    @staticmethod
    def serialize_delete_response(response: dtypes.RedisDeleteResponse) -> redis_pb2.RedisDeleteResponse: ...
    @staticmethod
    def deserialize_delete_response(proto: redis_pb2.RedisDeleteResponse) -> dtypes.RedisDeleteResponse: ...
    @staticmethod
    def serialize_ping_request(request: dtypes.RedisPingRequest = None) -> redis_pb2.RedisPingRequest: ...
    @staticmethod
    def deserialize_ping_request(proto: redis_pb2.RedisPingRequest) -> dtypes.RedisPingRequest: ...
    @staticmethod
    def serialize_ping_response(response: dtypes.RedisPingResponse) -> redis_pb2.RedisPingResponse: ...
    @staticmethod
    def deserialize_ping_response(proto: redis_pb2.RedisPingResponse) -> dtypes.RedisPingResponse: ...
    @staticmethod
    def serialize_get_cache_request(request: dtypes.RedisGetCacheRequest = None) -> redis_pb2.RedisGetCacheRequest: ...
    @staticmethod
    def deserialize_get_cache_request(proto: redis_pb2.RedisGetCacheRequest) -> dtypes.RedisGetCacheRequest: ...
    @staticmethod
    def serialize_get_cache_response(response: dtypes.RedisGetCacheResponse) -> redis_pb2.RedisGetCacheResponse: ...
    @staticmethod
    def deserialize_get_cache_response(proto: redis_pb2.RedisGetCacheResponse) -> dtypes.RedisGetCacheResponse: ...
    @staticmethod
    def serialize_clear_cache_request(request: dtypes.RedisClearCacheRequest = None) -> redis_pb2.RedisClearCacheRequest: ...
    @staticmethod
    def deserialize_clear_cache_request(proto: redis_pb2.RedisClearCacheRequest) -> dtypes.RedisClearCacheRequest: ...
    @staticmethod
    def serialize_clear_cache_response(response: dtypes.RedisClearCacheResponse) -> redis_pb2.RedisClearCacheResponse: ...
    @staticmethod
    def deserialize_clear_cache_response(proto: redis_pb2.RedisClearCacheResponse) -> dtypes.RedisClearCacheResponse: ...
