from proto_utils.database import dtypes as dtypes
from proto_utils.generated.database import utils_pb2 as utils_pb2

class DatabaseUtilsSerde:
    @staticmethod
    def serialize_api_response(api_response: dtypes.ApiResponse) -> utils_pb2.ApiResponse: ...
    @staticmethod
    def deserialize_api_response(proto: utils_pb2.ApiResponse) -> dtypes.ApiResponse: ...
    @staticmethod
    def serialize_property_type(property_type: dtypes.PropertyType) -> utils_pb2.PropertyType: ...
    @staticmethod
    def deserialize_property_type(proto: utils_pb2.PropertyType) -> dtypes.PropertyType: ...
    @staticmethod
    def serialize_properties(properties: dtypes.Properties) -> utils_pb2.Properties: ...
    @staticmethod
    def deserialize_properties(proto: utils_pb2.Properties) -> dtypes.Properties: ...
    @staticmethod
    def serialize_jsonschema(jsonschema: dtypes.JsonSchema) -> utils_pb2.JsonSchema: ...
    @staticmethod
    def deserialize_jsonschema(proto: utils_pb2.JsonSchema) -> dtypes.JsonSchema: ...
