# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ddl_generator.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ddl_generator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import clients.dtypes.dtypes_pb2 as dtypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x64l_generator.proto\x12\rddl_generator\x1a\x0c\x64types.proto\"\x8f\x01\n\nDDLRequest\x12\x18\n\x03\x61st\x18\x01 \x01(\x0b\x32\x0b.dtypes.AST\x12\x37\n\x07\x63olumns\x18\x02 \x03(\x0b\x32&.ddl_generator.DDLRequest.ColumnsEntry\x1a.\n\x0c\x43olumnsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa9\x05\n\x0b\x44\x44LResponse\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.dtypes.AstType\x12\x0b\n\x03sql\x18\x02 \x01(\t\x12\x16\n\x0cnumber_value\x18\x03 \x01(\x02H\x00\x12\x14\n\ntext_value\x18\x04 \x01(\tH\x00\x12\x17\n\rlogical_value\x18\x05 \x01(\x08H\x00\x12\x11\n\x04\x63\x65ll\x18\x06 \x01(\tH\x01\x88\x01\x01\x12%\n\x07refType\x18\x07 \x01(\x0e\x32\x0f.dtypes.RefTypeH\x02\x88\x01\x01\x12\x13\n\x06\x63olumn\x18\x08 \x01(\tH\x03\x88\x01\x01\x12\x11\n\x04\x65ror\x18\t \x01(\tH\x04\x88\x01\x01\x12\x12\n\x05start\x18\n \x01(\tH\x05\x88\x01\x01\x12\x10\n\x03\x65nd\x18\x0b \x01(\tH\x06\x88\x01\x01\x12\r\n\x05\x63\x65lls\x18\x0c \x03(\t\x12\x0f\n\x07\x63olumns\x18\r \x03(\t\x12\x12\n\x05\x65rror\x18\x0e \x01(\tH\x07\x88\x01\x01\x12\x15\n\x08operator\x18\x0f \x01(\tH\x08\x88\x01\x01\x12-\n\x04left\x18\x10 \x01(\x0b\x32\x1a.ddl_generator.DDLResponseH\t\x88\x01\x01\x12.\n\x05right\x18\x11 \x01(\x0b\x32\x1a.ddl_generator.DDLResponseH\n\x88\x01\x01\x12\x11\n\x04name\x18\x12 \x01(\tH\x0b\x88\x01\x01\x12-\n\targuments\x18\x13 \x03(\x0b\x32\x1a.ddl_generator.DDLResponse\x12\x30\n\x07operand\x18\x14 \x01(\x0b\x32\x1a.ddl_generator.DDLResponseH\x0c\x88\x01\x01\x42\x07\n\x05valueB\x07\n\x05_cellB\n\n\x08_refTypeB\t\n\x07_columnB\x07\n\x05_erorB\x08\n\x06_startB\x06\n\x04_endB\x08\n\x06_errorB\x0b\n\t_operatorB\x07\n\x05_leftB\x08\n\x06_rightB\x07\n\x05_nameB\n\n\x08_operand2V\n\x0c\x44\x44LGenerator\x12\x46\n\x0bGenerateDDL\x12\x19.ddl_generator.DDLRequest\x1a\x1a.ddl_generator.DDLResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ddl_generator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DDLREQUEST_COLUMNSENTRY']._loaded_options = None
  _globals['_DDLREQUEST_COLUMNSENTRY']._serialized_options = b'8\001'
  _globals['_DDLREQUEST']._serialized_start=53
  _globals['_DDLREQUEST']._serialized_end=196
  _globals['_DDLREQUEST_COLUMNSENTRY']._serialized_start=150
  _globals['_DDLREQUEST_COLUMNSENTRY']._serialized_end=196
  _globals['_DDLRESPONSE']._serialized_start=199
  _globals['_DDLRESPONSE']._serialized_end=880
  _globals['_DDLGENERATOR']._serialized_start=882
  _globals['_DDLGENERATOR']._serialized_end=968
# @@protoc_insertion_point(module_scope)
