# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import clients.ddl_generator.ddl_generator_pb2 as ddl__generator__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ddl_generator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DDLGeneratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateDDL = channel.unary_unary(
                '/ddl_generator.DDLGenerator/GenerateDDL',
                request_serializer=ddl__generator__pb2.DDLRequest.SerializeToString,
                response_deserializer=ddl__generator__pb2.DDLResponse.FromString,
                _registered_method=True)


class DDLGeneratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateDDL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DDLGeneratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateDDL': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDDL,
                    request_deserializer=ddl__generator__pb2.DDLRequest.FromString,
                    response_serializer=ddl__generator__pb2.DDLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ddl_generator.DDLGenerator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ddl_generator.DDLGenerator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DDLGenerator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateDDL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ddl_generator.DDLGenerator/GenerateDDL',
            ddl__generator__pb2.DDLRequest.SerializeToString,
            ddl__generator__pb2.DDLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
